name: hello world
on:
    push:
        paths:
            - "!readme.md"
            - "**js"
        branches:
            - "main"
            - "release/**"
            - "!dev/**"

    pull_request:
        type: [opened, reopened, synchronize, labeled, unlabeled]

    workflow_dispatch:
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - uses: mheap/github-action-required-labels@v2
                with:
                    mode: exactly
                    count: 0
                    labels: "do not build"
            - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
            - run: echo Hello World, today is $TODAY
            - run: docker image ls
